version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  tests:
    docker:
      - image: 'cimg/node:16.19.1'
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Run WebDriverIO tests
          command: |
            - echo "<< pipeline.parameters.browser >>"
            - npm i && npm run browserstack-multi
workflows:
  Automation:
    jobs:
      - tests
