version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: test
          command: BROWSERSTACK_USERNAME=jyothi75 BROWSERSTACK_ACCESS_KEY=7Qgr7zqwwsFJDyPy2PVW npm run browserstack-multi
