version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: 'cimg/node:16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run WebDriverIO tests
          command: npm run chrome
workflows:
  version: 2
  build:
    jobs:
      - build
