version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  tests:
    docker:
      - image: 'cimg/node:16.19.1'
    steps:
      - checkout
      - run:
          name: Run WebDriverIO tests
          command: npm install
          command: npm run chrome
workflows:
  Automation:
    jobs:
      - tests
