version: 2

jobs:
  tests:
    docker:
      - image: 'cimg/node:16.19.1'
    working_directory: ~/hioscar-wdio-cucumber
    steps:
      - checkout
      - run:
          name: Install Dependecies
          command: npm install
      - run:
          name: Print Echo
          command: echo $BROWSERSTACK_USERNAME
workflows:
  Automation:
    jobs:
      - tests
